### ISSUE TITLE
video importing doesn't works (Windows-VMware)

### ISSUE THREAD

**Issue by josebg16** [ibooij/big-ring#76]
I'm trying to set up in a Mac with VMware ( Windows 7).  Installation and Ant + recognitions is OK but importing videos takes for ever.

**Comment by ibooij** [comment]
Hi,

With forever, do you mean it never finishes?

Can you give a little more information on what your setup is?

1. What is the Video folder that you have configured in Big Ring?
2. What videos do you have there (and what control files)?

**Comment by josebg16** [comment]
Yes, it never finishes.

1. user/jose/Documents/Videos VLR
2. demo RLV from https://www.reallifevideo.de/rlv.php?rlv=galibier&lang=en (installed in the Videos VLR folder)

Thanks

**Comment by ibooij** [comment]
In the big ring, there is a file called `message.log`, could you attach the content of that file to this issue?

**Comment by josebg16** [comment]
Yes.
[message.log.zip](https://github.com/ibooij/big-ring/files/151293/message.log.zip)

**Comment by ibooij** [comment]
this log only contains messages that no ANT+ stick is found. 
Did you, by any chance, have more than one instance of Big Ring running?

Can you then try again (and send the log file) and also send a screenshot when Big Ring is importing?

**Comment by josebg16** [comment]
[message.log 2.zip](https://github.com/ibooij/big-ring/files/153002/message.log.2.zip)
![captura de pantalla 2016-03-01 a las 16 19 31](https://cloud.githubusercontent.com/assets/17549834/13431407/982aa3fe-dfc9-11e5-8d4c-6b7176b1dbdc.png)

Just one instance of Big Ring. the first time I opened the program I had problems with suunto ant + driver but after  an update the driver was well detected.

**Comment by ibooij** [comment]
Thanks for that.

This is a weird problem. According to the log file, no rlv (.rlv, .xml or .gpx) files are found.
If I set my video folder to a folder without any rlv files, the message box does get removed, I just won't have any videos in the list. As is expected.

**Can you show me a screenshot of your video folder (in a file explorer)?** 

I'm wondering if this a combination of VMWare and Windows, or if there's just a silly mistake somewhere in Big Ring.

Just make sure, could you please upgrade to version 1.8.0 that was released yesterday?

Thanks.

**Comment by josebg16** [comment]
The first time I opened the program I got a message: "the program can't start because MSVCR120.dll is missing...". I downloaded Visual C++ from microsoft (vcredist_x86.exe) and after installing the exe the message disappear.
![captura de pantalla 2016-03-01 a las 17 32 09](https://cloud.githubusercontent.com/assets/17549834/13433800/ba2982d6-dfd3-11e5-9d8e-e358c29cd4c8.png)
![captura de pantalla 2016-03-01 a las 17 32 49](https://cloud.githubusercontent.com/assets/17549834/13433801/bb2b7090-dfd3-11e5-8cf0-855ced1b3d5c.png)

**Comment by ibooij** [comment]
The missing DLL is a mistake I made in 1.7.0. It should be fixed in 1.8.0.

In your folders, I don't see a Tacx (.rlv and .pgmf) or VirtualTraining (.xml) file. 

If you use the installer from reallifevideo.de, the VirtualTraining file (`FR_Galibier_Demo.xml` in this case) should be installed in:
`C:\Users\USERNAME\Documents\VirtualTraining\RLV` (with `USERNAME` replaced by your own username of course). This file is needed because it contains several pieces of data, like the height profile for instance.

If you cannot find this file, you might try running the installer again.

The folder you point "Video Folders" to should contain both the movie files (.avi or .mp4) and the metadata files, like this .xml file.

Hope this helps

**Comment by josebg16** [comment]
Finally , I try with some rlv and pgmf and still not working. I tried in an old PC and I had the same problem :-(. Now  I`m trying to run the app on Ubuntu 14.04.4 (VMware on iMac) and I get the error in terminal:
/usr/include/c++/4.8/bits/stl_vector.h:919:7: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘std::vector<indoorcycling::virtualtrainingfileparser::DistanceMappingEntry>::value_type&& {aka indoorcycling::virtualtrainingfileparser::DistanceMappingEntry&&}’
make[1]: *** [virtualtrainingfileparser.o] Error 1
make[1]: se sale del directorio «/home/josebello/Documentos/BIGRING/mainlib»
make: *** [sub-mainlib-make_first] Error 2

This is Error from Qt5:

 /home/josebello/Documents/big-ring-release-1.8.0/mainlib/importer/virtualtrainingfileparser.cpp:228: error: no matching function for call to 'std::vector<indoorcycling::virtualtrainingfileparser::DistanceMappingEntry>::push_back(<brace-enclosed initializer list>)'
             entries.push_back({entry});
                                      ^ 


Thank you

**Comment by ibooij** [comment]
Hi,

I'm compiling on Ubuntu as well, on version 15.04 and 15.10. I have gcc
version 4.9.2, you seem to have 4.8. It might be that the construct used on
that line does not work on gcc 4.8. Looking at it, it isn't even needed.
Could you try something: On line 228 of
mainlib/importer/virtualtrainingfileparser.cpp,
remove the "{" and "}" surrounding the word entry, so it will look like
this:

entries.push_back(entry);


instead of


entries.push_back({entry});


Could you test if that makes things compile?

thanks,
Ilja

**Comment by josebg16** [comment]
Hi,
After gcc 4.9 and "entries.push_back(entry);" the error disappear but now Qt shows two errors:

/home/josebello/Documents/big-ring-release-1.8.0/mainlib/importer/reallifevideocache.cpp:34: error: 'Qt_5_4' is not a member of 'QDataStream'
 const int CACHE_FILE_QDATASTREAM_VERSION = QDataStream::Qt_5_4;
                                            ^
 error: [reallifevideocache.o] Error 1

thanks

**Comment by ibooij** [comment]
That might yo version of Qt that is too old. you probably have version 5.2
I think?

What you can do is change line 34 in mainlib/importer/reallifevideocache.cpp
to read:

const int CACHE_FILE_QDATASTREAM_VERSION = QDataStream::Qt_5_2;


If you have version 5.2 of Qt, this will work.

cheers,
Ilja

**Comment by ibooij** [comment]
Hi,

I just thought about your Qt version. You'll get more compile issues that
the one that you mentioned above. You will really need Qt 5.4 (or higher).

I'm still wondering about what the original source of the error is. You
said you tried with and old PC and it was still not working. We must be
overlooking something, because I have never seen this problem before. Can
you try on the older machine again, send me the message.log file and the
directory contents (screenshot?) of the videos folder. Perhaps we can fix
the problem that way.

cheers,
Ilja

**Comment by josebg16** [comment]
Hi,

The PC is a Compaq Presario C700. The message log don't show anything (empty) and the screen is the same as above but the video importing windows is not green and shows 0%. When I run Big Ring without the USB Ant + (suunto) the log is messed-NO-USB. In the video folder is a video (FR_AlpineClassic in a folder and the pgmf and rlv) the video works on Goldencheeth. Stray with other videos and with other path with the same results. The stunt USB works well (shows my heart rate garmin in ANT + sensors window)

[message-NO -USB.log.zip](https://github.com/ibooij/big-ring/files/183852/message-NO.-USB.log.zip)

thanks
cheers,

Jose

**Comment by ibooij** [comment]
Hi Jose,

I'll make a version with some more debugging information. This might help us getting some more information. Hopefully I can make it tonight, otherwise it will probably have to wait until the weekend. Sorry for that.

cheers,
Ilja

**Comment by josebg16** [comment]
Ok, I can't try nothing until a few days, so next week its fine  for me.

**Comment by josebg16** [comment]
Hi,

I've tried the last version you send me and I'm attaching de log file. This log file is when an external hard drive with all my videos is plug-in it. If I just configure to search one folder in the computer with a few videos (with  .rev and .pgmf files) the log is empty.

thanks, 
Jose
[message(Windows-1)1.txt](https://github.com/ibooij/big-ring/files/195707/message.Windows-1.1.txt)

**Comment by ibooij** [comment]
Well, at least all videos are found. The question now becomes: why are they
not imported.

**Comment by ibooij** [comment]
Logging should be better now (flushing to file after every message) and I added some extra log lines. Could you test again?

Download is here: https://www.dropbox.com/s/rxjh5erdqtc67qk/big-ring-windows-1.8.1.3.zip?dl=0

Thanks for perservering on this!

**Comment by josebg16** [comment]
Hi Lija,

I tried the new version. The log is attached.The main difference is that now all possible videos are listed but the problem persiste.
 I've tried to run the program (1.8) in another PC with another copy of windows and it  runs. That make me think that the problem could be related to the windows 7 copy or configuration. 
On the other hand I have a copy of Xcode and Qt 5.6 in my iMac. If you want I can help you to compile a Mac version (I don't know if it is possible). 

Thanks for all,
Jose
[message windows-1-2.txt](https://github.com/ibooij/big-ring/files/215149/message.windows-1-2.txt)

**Comment by ibooij** [comment]
> I tried the new version. The log is attached.The main difference is that now all possible videos are listed but the problem persiste.

What do you mean by "the problem persist"? The problem was the import, wasn't it?

It must be something with the configuration of Windows. However, I still think that Big Ring should _always_ work.

I think that most of big ring should compile on OS X. There are a few pieces of operating system specific code (Windows/Linux). Unfortunately I don't have a Mac, so I cannot test anything. If you could try it that would be great!

**Comment by josebg16** [comment]
Hi lija,

In the vmware image the log shows that the program see all videos in my hard drive but still not importing any video. In one Laptop I have the same problem but with another laptop (with other windows 7 copy) the videos are well imported. 
I have an iMac and a Mac Pro so I can test the app. Just let me know what to do or send me a copy and I will test  for you.

Thanks
Jose

**Comment by ibooij** [comment]
Hi Jose,

to build the application using QtCreator you should:
Download the sources or clone the git repository. Downloading can be done from https://github.com/ibooij/big-ring/archive/master.zip

After unzipping, open the project in QtCreator and build it. It'll probably give errors, I just don't know what errors yet..
